" シンタックスハイライト（色分け）
syntax on

set title

" 行の番号表示
set number

" 現在の行の強調
set cursorline

" 現在の行を強調表示（縦）
set cursorcolumn

" Tab文字を半角スペースに
set expandtab

" Tabの幅をスペース4個分に
set tabstop=4

" 行頭でのTabの幅をスペース4個分に
set shiftwidth=4

" コマンドラインの補完
set wildmode=list:longest

" コマンド補完
set wildmenu

" コマンドラインの補完
set wildmode=list:longest

" 保存時にsudo権限で保存 command : w!!
cnoremap w!! w !sudo tee > /dev/null %<CR>

" 検索時に大文字・小文字を区別する
set ignorecase

set background=dark
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1
colorscheme hybrid

" 自動的に後ろのかぎ括弧をつける
imap { {}<LEFT>
imap [ []<LEFT>
imap ( ()<LEFT>

" windowの下にterminalを開く
set splitbelow

" terminalサイズの指定
set termwinsize=7x0


"""""""""""""""
"dein.vimの設定
"""""""""""""""
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')
  
  " NERDTreeの追加
  call dein#add('scrooloose/nerdtree')
  
  " vim-gitgutterの追加
  call dein#add('airblade/vim-gitgutter')

  " vim-fugitiveの追加
  call dein#add('tpope/vim-fugitive')


  call dein#add('davidhalter/jedi-vim')

  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on

" NERDTreeをCtrl+Nで起動
map <C-n> :NERDTreeToggle<CR>

" ファイルを指定した場合は、NERDTreeを起動しない
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" jedi-vimでdocstringのポップアップ無効
autocmd FileType python setlocal completeopt-=preview
